### ISSUE TITLE
 Webpack 2 support

### ISSUE THREAD

**Issue by laggingreflex** [start-runner/webpack#15]
Would love to get notified when this gets webpack 2 support

**Comment by deepsweet** [comment]
ok, maybe `2.2.0-rc.2` is good enough to bump it here.

**Comment by laggingreflex** [comment]
I was wondering, perhaps maybe set it as `{"peerDependency": {"webpack": "*"}}` and leave it up to the user?

**Comment by deepsweet** [comment]
I don't really like `peerDependency` in case of Start because it'd be "implicit" dependency which you will never use directly 🤔  also there may be a case with different API among different versions.

anyway, I'll bump it today.

**Comment by deepsweet** [comment]
also what do you think about splitting this task into 2, `webpack` and `webpack-dev-server`? from one point of view it should be splitted by the concept. from another – there shouldn't be a case in this reality when you need only `webpack` but no `webpack-dev-server`.

**Comment by laggingreflex** [comment]
I like that idea. I actually keep "webpack" in "dependencies" and "webpack-dev-server" in "devDependencies" because I only need "webpack" to build in "production" environment.

**Comment by deepsweet** [comment]
but then you should keep all the Start baggage in "dependencies" to run `webpack` in production as well 🤔

**Comment by deepsweet** [comment]
anyway it shouldn't be worse than current solution, but may be better for someone's case. I will split it.

**Comment by deepsweet** [comment]
https://github.com/start-runner/webpack-dev-server

can't fully test it right now in real life env, any help is appreciated.
