### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by laggingreflex** [start-runner/webpack#16]
I've mostly ever used Webpack via its CLI which has a `--watch` option. 

So I was wondering how to do this in `start-webpack`? Using `start-watch` would trigger the whole webpack process again for every file change, right? which wouldn't be as optimal as using `webpack --watch` directly. 

I haven't used [gulp-webpack](https://github.com/shama/webpack-stream#usage) but it seems to support watch mode in the module itself without relying on outer gulp's watch mode. I haven't read the complete source (or used it, like I said) but they seems to have added this feature in: https://github.com/shama/webpack-stream/blob/master/index.js#L148

**Comment by deepsweet** [comment]
have you tried to pass [`watch: true`](https://github.com/shama/webpack-stream/blob/9899b5b8423c512c9000f7f27367a7e519e7a68d/index.js#L105) to config?

**Comment by laggingreflex** [comment]
Ah, it works, thanks! Didn't occur to me to put the CLI option in the config, but it works
```js
import webpackConfig from './webpack.config';
export const wp = () => start(
  webpack.build({...webpackConfig, watch: true})
);
```
